# [2023/5/6]
# The configs file for Cluster

config : "configs/config.yaml"
mode : "run"
method : "DBSCAN"
is_normalize : False
normalize_method : "min-max"
decomposition_method : "UMAP"
select_num : 10